-- VibeSpace account / usage-history schema
-- Run this in Supabase SQL Editor.

create table if not exists public.usage_records (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  started_at timestamptz not null,
  ended_at timestamptz not null,
  duration_seconds integer not null check (duration_seconds >= 0),
  operation_mode text,
  avg_db double precision,
  acoustic_profile text,
  created_at timestamptz not null default now()
);

create index if not exists usage_records_user_started_idx
  on public.usage_records (user_id, started_at desc);

alter table public.usage_records enable row level security;

drop policy if exists "Users can read their own usage records" on public.usage_records;
create policy "Users can read their own usage records"
  on public.usage_records
  for select
  using (auth.uid() = user_id);

drop policy if exists "Users can insert their own usage records" on public.usage_records;
create policy "Users can insert their own usage records"
  on public.usage_records
  for insert
  with check (auth.uid() = user_id);

drop policy if exists "Users can delete their own usage records" on public.usage_records;
create policy "Users can delete their own usage records"
  on public.usage_records
  for delete
  using (auth.uid() = user_id);

grant usage on schema public to authenticated;

grant select, insert, delete
on table public.usage_records
to authenticated;

grant usage, select
on sequence public.usage_records_id_seq
to authenticated;

revoke all
on table public.usage_records
from anon;
